
name: JAVA Build
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
        
            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                distribution: 'adopt'
                java-version: '11'
            - name: Build and run Java files
              run: |
                patterns=("FactoryPattern" "ObserverPattern","SingletonePattern","AbstractFactorypattern")
        
                for pattern in "${patterns[@]}"; do
                cd "$pattern"
                javac *.java
                java -cp . Main
                cd ../
                done